---
title: "Data Science Language Analysis"
subtitle: <h1><u>EDA Report</u></h1>
author: 
  - "Nazli Ozum Kafaee"
  - "Prash Medirattaa"
  - "Avinash Prabhakaran"
date: '2018-04-15'
output:
  html_document:
    keep_md: yes
    toc: true
    toc_float: true
    theme: united
    highlight: tango
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
#Loading the required packages
suppressPackageStartupMessages(library(tidyverse))
```

```{r}
#Reading in processed data. 
responses <- read.csv(file = "../docs/survey_results_clean.csv")
```


```{r}
#Binary encoding the response variable. Python -> 1; R -> 0 
data <- responses %>% mutate(binary = if_else(preference == "Python", 1, 0))

#Releveling the reference task from Data Viz -> Machine Learning
data_relevel <- data
data_relevel$task <-relevel(data$task,ref="Machine Learning")

#Fitting a GLM without any confounding variables.
mod <- glm(binary ~ task, data = data)
summary(mod)
```

```{r}
mod <- glm(binary ~ task, data = data_relevel)
summary(mod)
```


```{r}
#Fitting GLM with all the confounding variables.
responses %>% colnames()

mod <- glm(binary ~ task + background + experience + attitude + first + active, data = data)
summary(mod)
```



```{r}
mod <- glm(binary ~ task + background + experience + attitude + first + active, data = data_relevel)
summary(mod)
```


```{r}
#Removing Attitude as Confounder as change
mod <- glm(binary ~ task + background + experience + attitude + first + active, data = data)
summary(mod)
```


```{r}
#Removing Attitude as Confounder as change
mod <- glm(binary ~ task + background + experience + first + active, data = data_relevel)
summary(mod)
```
```{r}
#Removing Experience as Confounder
mod <- glm(binary ~ task + background + first + active, data = data)
summary(mod)
```



```{r}
#Removing Experience as Confounder
mod <- glm(binary ~ task + background + first + active, data = data_relevel)
summary(mod)
```





```{r}
#Removing active as Confounder
mod <- glm(binary ~ task + background + first, data = data)
summary(mod)
```



```{r}
#Removing active as Confounder
mod <- glm(binary ~ task + background + first, data = data_relevel)
summary(mod)
```



```{r}
#Removing first as Confounder
mod <- glm(binary ~ task + background, data = data)
summary(mod)
```



```{r}
#Removing first as Confounder
mod <- glm(binary ~ task + background, data = data_relevel)
summary(mod)
```


**Not Removing first language as the AIC score of the model increases from 94.689 to 97.83.**

```{r}
#Removing background as Confounder
mod <- glm(binary ~ task + first, data = data)
summary(mod)
```



```{r}
#Removing background as Confounder
mod <- glm(binary ~ task + first, data = data_relevel)
summary(mod)
```

**Removing Background as confounder as the model with only first language as confounder gives the lowest AIC score**


#Final Model

```{r}
#Model with first language and background
mod <- glm(binary ~ task + first, data = data)
summary(mod)
```

```{r}
model <- glm(binary ~ task + first, data = data_relevel)
summary(model)

#Adjusting for p-values.(Not required anymore after chat with Tiffany)
#p.vals <- summary(model)$coef[,4]
#p.adjust(p.vals ,method = "BH") < 0.05
```

```
#Not Required to Relevel the confounders.
#Releveling the reference task from Data Viz -> Machine Learning
#Releveling the reference first language from C -> R
data_relevel <- data
data_relevel$task <-relevel(data$task,ref="Machine Learning")
data_relevel$first <-relevel(data$first,ref="R")

model <- glm(binary ~ task + first, data = data_relevel)
summary(model)
```